// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUIjZBBzAPZ83p1yDPCOAra-ErOs9K2ls',
    appId: '1:1045472240686:android:30a67f49892fee138febbf',
    messagingSenderId: '1045472240686',
    projectId: 'friday-683ad',
    storageBucket: 'friday-683ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzb8FYxi0tSHoK4YQa63ZcLAwzomyAy0',
    appId: '1:1045472240686:ios:c37220ac9abcc6da8febbf',
    messagingSenderId: '1045472240686',
    projectId: 'friday-683ad',
    storageBucket: 'friday-683ad.appspot.com',
    androidClientId: '1045472240686-q3fnk5dg2ra4lg4u3ufqe2pkj74gm6st.apps.googleusercontent.com',
    iosClientId: '1045472240686-m2blkie00hbu64eq9lujisane5l9ihef.apps.googleusercontent.com',
    iosBundleId: 'com.avinashkranjan.friday',
  );
}
